[package]
name    = "todotxt-tui"
version = "1.5.0"
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "todotxt-tui"
path = "src/main.rs"

[dependencies]
ratatui      = { workspace = true }
crossterm    = { workspace = true }
color-eyre   = { workspace = true }
chrono       = { workspace = true }
serde        = { workspace = true }
toml         = { workspace = true }
thiserror    = { workspace = true }
directories  = { workspace = true }
clap         = { workspace = true }
todotxt-core = { path = "../todotxt-core", features = ["watching"] }
tui-textarea = { workspace = true }
arboard      = "=3.6.1"

[dev-dependencies]
tempfile = { workspace = true }
