[package]
name = "todotxt-core"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
winnow = { workspace = true }
tempfile = { workspace = true }
notify-debouncer-mini = { workspace = true, optional = true }

[features]
watching = ["dep:notify-debouncer-mini"]

[dev-dependencies]
rstest = "0.26"
insta = { version = "1.47", features = ["json"] }
